### ISSUE TITLE
Verify images are actually images

### ISSUE THREAD

**Issue by UberKitten** [NelsonLeDuc/CalmanBot#1]
When an image is posted, start streaming the first few bytes and check that it has a valid PNG, JPG, or GIF header: http://www.mikekunz.com/image_file_header.html 

If it's not valid, then choose the next image in the search. Should cut down on images that are invalid or require a proper referrer, etc.

**Comment by NelsonLeDuc** [comment]
I'll go ahead and implement this, a few things need to be reworked to enable this in a good way though

**Comment by UberKitten** [comment]
Good work, lackey.

## 

Michael West
https://mwe.st

On Jul 20, 2015 8:34 PM, Nelson LeDuc notifications@github.com wrote:

Closed #1https://github.com/NelsonLeDuc/CalmanBot/issues/1.
