### ISSUE TITLE
PasteBin spam detection

### ISSUE THREAD

**Issue by UberKitten** [NelsonLeDuc/CalmanBot#10]
PasteBin thinks the copypasta CalmanBot posts is spam.

![Possible spam detected](http://i.imgur.com/cCnJjo7.png)

It doesn't make much sense to reupload copypasta every time. Nobody clicks on it. Truncate the copypasta if it's too long or just pick another one.

**Comment by NelsonLeDuc** [comment]
This is exclusive to GroupMe support which is basically dead
