### ISSUE TITLE
Clarify YouTube commands

### ISSUE THREAD

**Issue by UberKitten** [NelsonLeDuc/CalmanBot#16]
Which one picks the search at random? On Google, Feeling Lucky means you pick the first result, so it's not very clear.
```
@CalmanBot youtube (.*)                                
    Youtube search
@CalmanBot \$youtube (.*)                              
    Feeling Lucky? Youtube search
```

Also, DuckDuckGo uses ! for Feeling Lucky, might be worth adding it in too.

**Comment by NelsonLeDuc** [comment]
Completed
