### ISSUE TITLE
Handling leading whitespace and other characters

### ISSUE THREAD

**Issue by magicspacekiwi** [NelsonLeDuc/CalmanBot#4]
If whitespace precedes a mention, a response is not generated.

Should CalmanBot simply trim the whitespace around messages before attempting to parse them, or should the bot respond even when mentioned within a message, parsing characters that come after the mention?

For example, "we need more @calmanbot bacon" would be parsed with "bacon" as the message.

**Comment by NelsonLeDuc** [comment]
Fixed in v1.2.6
