### ISSUE TITLE
Change lol 12

### ISSUE THREAD

**Issue by UberKitten** [NelsonLeDuc/CalmanBot#7]
make it better text thx

**Comment by NelsonLeDuc** [comment]
@T3hUb3rK1tten What would you suggest?

**Comment by UberKitten** [comment]
Pull the top 100 posts in /r/copypasta, pick a self post at random, and then pick a random sentence or two in the text of that post.

Or I can get you a database of copypasta to pull a sentence or two from.

## 

Michael West
https://mwe.st
