### ISSUE TITLE
SLOW

### ISSUE THREAD

**Issue by UberKitten** [NelsonLeDuc/CalmanBot#8]
- [x] It is slow
- [ ] Make it faster

**Comment by magicspacekiwi** [comment]
+1

**Comment by UberKitten** [comment]
#notfixed

## 

Michael West
https://mwe.st

On Jan 29, 2016 4:25 AM, Nelson LeDuc notifications@github.com wrote:

Closed #8https://github.com/NelsonLeDuc/CalmanBot/issues/8.

##
